# exemples Algebra

In [7]:
import numpy as np

exemples de vectors (s anomenen arrays )

In [8]:
v=np.array([1,0,0])
u=np.array([0,-2,0])

In [9]:
print(v)

[1 0 0]


In [14]:

print(w2)

[ 1 -2  0]


podem fer suma resta producte escalar i vectorial

In [15]:
np.dot(u,v)

np.int64(0)

In [16]:
a=np.dot(u,v)
print(a)


0


In [18]:
b=np.cross(v,u)
print(b)

[ 0  0 -2]


podem treballar amb matrius tambe

In [33]:
M=np.array([[2,2],[1,3]])
print(M)

[[2 2]
 [1 3]]


In [34]:
e=M[0,1]
print(e)

2


In [35]:
v=M[1,:] #els dos punts volen dir que agafi tots els numeros, és un comodin, en aquest cas li diem que el vector és tota la 2a fila
print(v)

[1 3]


valors i vectors propois

In [55]:
print (M) 

[[2 2]
 [1 3]]


In [56]:
#per trobar valor si vectors propis, li demanem linalg.eig(Matriu)
valors,vectors=np.linalg.eig(M)
print("valors propis", valors)
print("vectors propis", vectors)

valors propis [1. 4.]
vectors propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [57]:
u=vectors[:,0]
print(u)

[-0.89442719  0.4472136 ]


In [58]:
#per multiplicar matriu per vectors també fem servir np.dot, podem comprovar que efectivament són vectors propis
z=np.dot(M,v)
print(z)

[ 8 10]


altres exemples de matrius utils

In [61]:
A=np.zeros([3,3])
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
